Repository opendistro-for-elasticsearch/opendistro-build, pull requests merged in 2020-09, with the labels that each got.

#358 allow customizing docker registry
  helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
  helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
  helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
  helm/opendistro-es/templates/kibana/kibana-deployment.yaml
  helm/opendistro-es/values.yaml
Labels: Helm, enhancement

#380 Update Helm Readme based on #35 & #358 PR
  helm/README.md
Labels: documentation

#384 Disable optimizations for knn library during docker build
  elasticsearch/docker/templates/Dockerfile.j2
Labels: bug fix

#385 update readme to fix #379
  helm/README.md
Labels: Helm, documentation

#383 Add locally run script to create ODFE distro release notes based on plugin release notes
  bin/releasenotes-orig-urls.txt
  bin/releasenotes.sh
Labels: enhancement

#392 Add ODFE 1.10.1 distro release notes
  release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
Labels: documentation
